[versions]
# Tool
checkstyle = "11.0.0"
spotless = "8.10.4"
shadow = "9.0.2"
gremlin = "0.0.9"
runTask = "2.3.1"
resourceFactory = "1.3.0"

# Java
jspecify = "1.0.0"
guice = "7.0.0"
caffeine = "3.2.2"
fastUuid = "0.2.0"

# Database
h2 = "2.3.232"
mysql = "9.4.0"
mariadb = "3.5.5"
postgresql = "42.7.7"
hikariCP = "7.0.2"
jdbi = "3.50.0-SNAPSHOT"
flyway = "11.11.2"

# Minecraft
configurate = "4.2.0"
adventure = "4.24.0"
paperApi = "1.21.8-R0.1-SNAPSHOT"
miniPlaceholders = "3.0.1"
doburoku = "1.0.0-SNAPSHOT"

# Test
junit = "5.13.4"

[libraries]
# Tool
spotless = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless"}

# Java
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
guice = { group = "com.google.inject", name = "guice", version.ref = "guice"}
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine"}
fastUuid = { group = "com.eatthepath", name = "fast-uuid", version.ref = "fastUuid" }

# Database
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
mysql = { group = "com.mysql", name = "mysql-connector-j", version.ref = "mysql" }
mariadb = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "mariadb" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
hikariCP = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikariCP"}
jdbiCore = { group = "org.jdbi", name = "jdbi3-core", version.ref = "jdbi"}
jdbiPostgres = { group = "org.jdbi", name = "jdbi3-postgres", version.ref = "jdbi"}
jdbiGuice = { group = "org.jdbi", name = "jdbi3-guice", version.ref = "jdbi"}
jdbiSqlObject = { group = "org.jdbi", name = "jdbi3-sqlobject", version.ref = "jdbi"}
flyway = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway"}
flywayMysql = { group = "org.flywaydb", name = "flyway-mysql", version.ref = "flyway" }
flywayPostgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }

# Minecraft
configurateHocon = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate" }
adventureApi = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApi"}
miniPlaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniPlaceholders" }
doburokuStandard = { group = "io.github.namiuni", name = "doburoku-standard", version.ref = "doburoku"}
doburokuAnnotationProcessor = { group = "io.github.namiuni", name = "doburoku-annotation-processor", version.ref = "doburoku"}

# Test
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }

[bundles]
testing = [
    "junit-api",
    "junit-engine"
]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
resourceFactory = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "resourceFactory" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runTask" }
gremlin = { id = "xyz.jpenilla.gremlin-gradle", version.ref = "gremlin" }
